# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8e553edf56c494e83e9ff5b9bea999fb679eb63d2700304b6656d8b959b283799a4ab229f7060a62bbb2e0402ecc48c7b28a81e93f52605062da04478fbe7e

test:
  secret_key_base: dfd7e53673250264a98dac6c1d86b99d07d69d61fb8b1e448021738e65b189724de430e521ffc13671b2a83a62728bf2faeb62c2c35ed0b125437a23686bb417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
